# Generated by Django 4.2.16 on 2026-04-26 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('department', models.CharField(choices=[('general', 'عمومی'), ('technical', 'فنی'), ('billing', 'مالی'), ('sales', 'فروش')], default='general', max_length=50, verbose_name='دپارتمان')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('urgent', 'فوری')], default='medium', max_length=50, verbose_name='اولویت')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_attachments/', verbose_name='فایل پیوست')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('in_progress', 'در حال بررسی'), ('resolved', 'حل شده'), ('closed', 'بسته شده')], default='pending', max_length=50, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت پشتیبانی',
                'verbose_name_plural': 'تیکت\u200cهای پشتیبانی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_reply_attachments/', verbose_name='فایل پیوست')),
                ('is_staff_reply', models.BooleanField(default=False, verbose_name='پاسخ کارمند')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='support.supportticket', verbose_name='تیکت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_replies', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پاسخ تیکت',
                'verbose_name_plural': 'پاسخ\u200cهای تیکت',
                'ordering': ['created_at'],
            },
        ),
    ]
