# Generated by Django 4.2.16 on 2026-04-28 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'support ticket ', 'verbose_name_plural': 'support tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketreply',
            options={'ordering': ['created_at'], 'verbose_name': 'ticket response ', 'verbose_name_plural': ' ticket responses'},
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='support_attachments/', verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='department',
            field=models.CharField(choices=[('general', 'عمومی'), ('technical', 'فنی'), ('billing', 'مالی'), ('sales', 'فروش')], default='general', max_length=50, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('urgent', 'فوری')], default='medium', max_length=50, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('in_progress', 'در حال بررسی'), ('resolved', 'حل شده'), ('closed', 'بسته شده')], default='pending', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='client '),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='support_reply_attachments/', verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='is_staff_reply',
            field=models.BooleanField(default=False, verbose_name='is_staff_reply'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='support.supportticket', verbose_name='ticket'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_replies', to=settings.AUTH_USER_MODEL, verbose_name='client'),
        ),
    ]
