# Generated by Django 4.2.16 on 2026-04-28 10:19

from django.db import migrations, models
import django.db.models.deletion
import shop.utils.image_uploders


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='base category name --- farsi')),
                ('en_name', models.CharField(max_length=50, unique=True, verbose_name='base category name --- english')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.utils.image_uploders.upload_BaseCategory_image_path, verbose_name='base category image')),
            ],
            options={
                'verbose_name': 'Base Category',
                'verbose_name_plural': 'Base Categories',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='category name ---farsi')),
                ('en_name', models.CharField(max_length=20, unique=True, verbose_name='category name ---english')),
                ('description', models.TextField(verbose_name='description ')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.utils.image_uploders.upload_cat_image_path, verbose_name='category image')),
                ('base_catgory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='categories.basecategories', verbose_name='main category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.category', verbose_name=' parent category ')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
    ]
