# Generated by Django 4.2.16 on 2026-04-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecategories',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='base_categories', to='public.brand', verbose_name='base category Brands'),
        ),
    ]
