# Generated by Django 4.2.16 on 2026-04-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_basecategories_brands'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
