# Generated by Django 4.2.16 on 2026-04-26 15:14

from django.db import migrations, models
import django.db.models.deletion
import shop.utils.image_uploders


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان اسلاید')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='زیرعنوان اسلاید')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.utils.image_uploders.upload_slider_image_path, verbose_name='تصویر اسلاید')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'اسلایدر صفحه اصلی',
                'verbose_name_plural': 'اسلایدرهای صفحه اصلی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان بنر')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.utils.image_uploders.upload_banner_image_path, verbose_name='تصویر بنر')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('position', models.CharField(choices=[('top', 'بالای صفحه'), ('middle', 'وسط صفحه'), ('bottom', 'پایین صفحه')], default='middle', max_length=10, verbose_name='موقعیت در صفحه')),
                ('size', models.CharField(choices=[('full', 'تمام عرض'), ('half', 'نیم عرض'), ('third', 'یک سوم')], default='full', max_length=10, verbose_name='اندازه بنر')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنرهای تبلیغاتی',
                'ordering': ['position', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.brand', verbose_name='برند')),
            ],
            options={
                'verbose_name': 'برند ویژه',
                'verbose_name_plural': 'برندهای ویژه',
                'ordering': ['order'],
            },
        ),
    ]
