# Generated by Django 4.2.16 on 2026-04-28 14:58

from django.db import migrations, models
import django.db.models.deletion
import shop.utils.image_uploders


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_alter_basecolor_options_alter_brand_options_and_more'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuredbrand',
            options={'ordering': ['order'], 'verbose_name': ' Featured Brand', 'verbose_name_plural': 'Featured Brands '},
        ),
        migrations.AlterModelOptions(
            name='homeslider',
            options={'ordering': ['order'], 'verbose_name': 'index page slider', 'verbose_name_plural': 'index page sliders'},
        ),
        migrations.AlterModelOptions(
            name='promotionalbanner',
            options={'ordering': ['position', 'order'], 'verbose_name': 'Promotional Banner', 'verbose_name_plural': 'Promotional Banners '},
        ),
        migrations.AlterField(
            model_name='featuredbrand',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='featuredbrand',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='featuredbrand',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.utils.image_uploders.upload_slider_image_path, verbose_name='Slide image '),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='slid order'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Slide subtitle  '),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Slide title'),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.utils.image_uploders.upload_banner_image_path, verbose_name='Banner image'),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='position',
            field=models.CharField(choices=[('top', 'بالای صفحه'), ('middle', 'وسط صفحه'), ('bottom', 'پایین صفحه')], default='middle', max_length=10, verbose_name='Banner position '),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='size',
            field=models.CharField(choices=[('full', 'تمام عرض'), ('half', 'نیم عرض'), ('third', 'یک سوم')], default='full', max_length=10, verbose_name='Banner size'),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banner title'),
        ),
    ]
