# Generated by Django 4.2.16 on 2026-04-28 10:19

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import shop.utils.image_uploders


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام رنگ')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#FF0000', 'red'), ('#008000', 'green'), ('#0000FF', 'blue')], verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'رنگ پایه',
                'verbose_name_plural': 'رنگ های پایه',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL'), ('4XL', '4XL')], max_length=10, null=True, verbose_name='سایز')),
                ('number_size', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سایز عددی (برای مواردی مثل کفش)')),
                ('size_numrical', models.CharField(max_length=10, verbose_name='سایز عددی نوشتاری')),
                ('category', models.CharField(blank=True, choices=[('clothing', 'لباس'), ('shoes', 'کفش'), ('accessories', 'اکسسوری')], max_length=20, null=True, verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'سایز',
                'verbose_name_plural': 'سایزها',
                'ordering': ['number_size'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام رنگ')),
                ('hex_code', models.CharField(help_text=' مثال: #FFFFFF', max_length=7, verbose_name='کد هگز رنگ')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.utils.image_uploders.upload_color_image_path, verbose_name='تصویر رنگ')),
                ('base_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='public.basecolor', verbose_name='رنگ پایه')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام ---فارسی')),
                ('en_name', models.CharField(max_length=50, unique=True, verbose_name='نام ---انگلیسی')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=shop.utils.image_uploders.upload_brand_image_path, verbose_name='لوگو برند')),
                ('category', models.ManyToManyField(blank=True, to='categories.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
            },
        ),
    ]
