# Generated by Django 4.2.16 on 2026-04-28 11:38

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import shop.utils.image_uploders


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_options'),
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecolor',
            options={'verbose_name': 'Base Color', 'verbose_name_plural': 'Base Colors'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'color', 'verbose_name_plural': 'colors'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['number_size'], 'verbose_name': 'size', 'verbose_name_plural': 'sizes '},
        ),
        migrations.AlterField(
            model_name='basecolor',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#FF0000', 'red'), ('#008000', 'green'), ('#0000FF', 'blue')], verbose_name='color value <-->(hex)'),
        ),
        migrations.AlterField(
            model_name='basecolor',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='base color name '),
        ),
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(blank=True, to='categories.category', verbose_name='Brand caregory'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='en_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name---english'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=shop.utils.image_uploders.upload_brand_image_path, verbose_name='Brand logo'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name---fasri'),
        ),
        migrations.AlterField(
            model_name='color',
            name='base_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='public.basecolor', verbose_name='base color  '),
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(help_text=' مثال: #FFFFFF', max_length=7, verbose_name='color value <-->(hex)'),
        ),
        migrations.AlterField(
            model_name='color',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.utils.image_uploders.upload_color_image_path, verbose_name='image for color '),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, verbose_name='colr name'),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(blank=True, choices=[('clothing', 'لباس'), ('shoes', 'کفش'), ('accessories', 'اکسسوری')], max_length=20, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='size',
            name='number_size',
            field=models.PositiveSmallIntegerField(blank=True, help_text='for shoes or etc... (*postive int*) ', null=True, verbose_name='Numrical size '),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL'), ('4XL', '4XL')], max_length=10, null=True, verbose_name='ware size '),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_numrical',
            field=models.CharField(help_text='write able', max_length=10, verbose_name='Numrical size '),
        ),
    ]
