# Generated by Django 4.2.16 on 2026-05-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_alter_basecolor_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام گارانتی')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='شرکت ارائه دهنده')),
                ('duration', models.PositiveIntegerField(help_text='مدت زمان گارانتی به ماه', verbose_name='مدت گارانتی (ماه)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('terms_conditions', models.TextField(blank=True, verbose_name='شرایط و ضوابط')),
                ('support_phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس پشتیبانی')),
                ('registration_required', models.BooleanField(default=False, verbose_name='نیاز به ثبت گارانتی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'گارانتی',
                'verbose_name_plural': 'گارانتی\u200cها',
                'ordering': ['name'],
            },
        ),
    ]
