# Generated by Django 4.2.16 on 2026-05-23 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['-created_at'], 'verbose_name': 'Provider', 'verbose_name_plural': 'Providers'},
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='can_sell',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='name',
        ),
        migrations.AddField(
            model_name='provider',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='provider',
            name='company_name',
            field=models.CharField(default='tets', help_text='Display name of the provider', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='economic_code',
            field=models.CharField(blank=True, help_text='Economic code', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='is_phone_verified'),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Registered/legal company name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='providers/logos/'),
        ),
        migrations.AddField(
            model_name='provider',
            name='national_id',
            field=models.CharField(blank=True, help_text='National ID for individual/company', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='phone_number'),
        ),
        migrations.AddField(
            model_name='provider',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='provider_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='company', max_length=20),
        ),
        migrations.AddField(
            model_name='provider',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='provider',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Company registration number', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='sheba',
            field=models.CharField(blank=True, help_text='IBAN / Sheba number', max_length=34, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='provider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='verification_code'),
        ),
        migrations.AddField(
            model_name='provider',
            name='verification_code_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='verification_code_created_at'),
        ),
        migrations.AddField(
            model_name='provider',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='user',
            field=models.OneToOneField(help_text='Main account owner of the provider', on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProviderMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='providers.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='providermember',
            constraint=models.UniqueConstraint(fields=('provider', 'user'), name='unique_provider_user_membership'),
        ),
    ]
