# Generated by Django 4.2.16 on 2026-05-28 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_provider_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['-created_at'], 'permissions': [('verify_provider', 'Can verify provider')], 'verbose_name': 'Provider', 'verbose_name_plural': 'Providers'},
        ),
    ]
