# Generated by Django 6.0.6 on 2026-06-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_alter_provider_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['-created_at'], 'permissions': [('verify_provider', 'Can verify provider'), ('manage_provider', 'Can manage provider')], 'verbose_name': 'Provider', 'verbose_name_plural': 'Providers'},
        ),
    ]
