# Generated by Django 4.2.16 on 2026-04-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='نامک')),
                ('content', models.TextField(verbose_name='محتوای مقاله')),
                ('short_description', models.TextField(blank=True, max_length=300, null=True, verbose_name='توضیح کوتاه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='تصویر مقاله')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان متا')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات متا')),
                ('meta_keywords', models.CharField(blank=True, max_length=300, null=True, verbose_name='کلمات کلیدی متا')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-created_at'],
            },
        ),
    ]
