# Generated by Django 4.2.16 on 2026-04-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('پرداخت شده', 'پرداخت شده'), ('در انتظار پرداخت', 'در انتظار پرداخت'), ('در انتظار تایید', 'در انتظار تایید'), ('ناموفق', 'ناموفق'), ('لغو شده', 'لغو شده')], default='در انتظار پرداخت', max_length=20, verbose_name='payment_status'),
        ),
    ]
