# Generated by Django 4.2.16 on 2026-04-28 11:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shop.utils.image_uploders


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0003_alter_category_options'),
        ('public', '0002_alter_basecolor_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='image')),
                ('categories', models.ManyToManyField(to='categories.category', verbose_name='categories')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('weight', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='weight to geram')),
                ('is_active_package', models.BooleanField(default=False, verbose_name='is active')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.BigIntegerField(verbose_name='base price')),
                ('final_price', models.BigIntegerField(default=0, editable=False, verbose_name='final price ')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='discount percentage')),
                ('is_active_discount', models.BooleanField(default=False, verbose_name='active discount ')),
                ('sold_count', models.PositiveIntegerField(default=0, verbose_name='sold_count')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='views_count')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='rate')),
                ('brand', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.brand', verbose_name='brand')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.color', verbose_name='color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_packages', to='products.product')),
                ('size', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.size')),
            ],
            options={
                'verbose_name': 'product package  ',
                'verbose_name_plural': ' product packages',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.utils.image_uploders.upload_image_path, verbose_name='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'gallery',
            },
        ),
    ]
