# Generated by Django 4.2.16 on 2026-04-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpackage',
            name='attributs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
