# Generated by Django 4.2.16 on 2026-05-23 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_warranty'),
        ('providers', '0001_initial'),
        ('products', '0002_productpackage_attributs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpackage',
            options={'permissions': [('can_publish_product', 'Can publish product'), ('can_see_sales_stats', 'Can see sales statistics')], 'verbose_name': 'product package  ', 'verbose_name_plural': ' product packages'},
        ),
        migrations.AddField(
            model_name='productpackage',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='providers.provider'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpackage',
            name='waranty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_packages', to='public.warranty'),
            preserve_default=False,
        ),
    ]
