# Generated by Django 4.2.16 on 2026-05-23 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productpackage_options_productpackage_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpackage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_packages', to='products.product'),
        ),
    ]
