# Generated by Django 4.2.16 on 2026-05-28 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_provider_options_and_more'),
        ('products', '0004_alter_productpackage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='providers.provider'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productpackage',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_packageser', to='providers.provider'),
        ),
    ]
