# Generated by Django 4.2.16 on 2026-05-28 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_provider_options_and_more'),
        ('products', '0005_product_provider_alter_productpackage_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='providers.provider'),
        ),
    ]
