# Generated by Django 4.2.16 on 2026-05-28 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('manage_own_products', 'Can manage own products')], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productpackage',
            options={'permissions': [('manage_own_packages', 'Can manage own packages')], 'verbose_name': 'product package  ', 'verbose_name_plural': ' product packages'},
        ),
    ]
