# Generated by Django 4.2.16 on 2026-04-26 15:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shop.account.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discount', models.PositiveIntegerField(help_text='درصد یا مبلغ تخفیف')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_coupons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='شماره تلفن')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='تأیید شماره تلفن')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='کد تأیید')),
                ('verification_code_created_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ایجاد کد تأیید')),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='کد ملی باید دقیقاً 10 رقم باشد', regex='^\\d{10}$'), shop.account.models.validate_national_id], verbose_name='کد ملی')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='شغل')),
                ('economic_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='کد اقتصادی')),
                ('legal_info', models.TextField(blank=True, null=True, verbose_name='اطلاعات حقوقی')),
                ('refund_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='روش بازگرداندن پول')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('notification_type', models.CharField(choices=[('info', 'اطلاعات'), ('success', 'موفقیت'), ('warning', 'هشدار'), ('danger', 'خطر')], default='info', max_length=20, verbose_name='نوع اعلان')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('related_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک مرتبط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavouriteProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(to='products.product', verbose_name='محصولات مورد علاقه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_address', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('full_address', models.TextField()),
                ('postcode', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
