# Generated by Django 4.2.16 on 2026-04-28 14:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shop.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='favouriteproducts',
            name='products',
            field=models.ManyToManyField(to='products.product', verbose_name='FavouriteProducts'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='is_read'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Notification message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'اطلاعات'), ('success', 'موفقیت'), ('warning', 'هشدار'), ('danger', 'خطر')], default='info', max_length=20, verbose_name='Notification Type '),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='related_url'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Notification title'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name=' birth_date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='economic_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='economic_code'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='is_phone_verified'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='job'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='legal_info',
            field=models.TextField(blank=True, null=True, verbose_name='legal_info'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='کد ملی باید دقیقاً 10 رقم باشد', regex='^\\d{10}$'), shop.account.models.validate_national_id], verbose_name='national_id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='refund_method',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='refund_method'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='verification_code'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification_code_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='verification_code_created_at'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='discount',
            field=models.PositiveIntegerField(help_text='discount'),
        ),
    ]
