# Generated by Django 6.0.6 on 2026-07-02 06:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_notification_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('discount_percent', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('max_discount_amount', models.PositiveIntegerField(default=0, verbose_name='حداکثر مبلغ تخفیف (تومان)')),
                ('min_order_amount', models.PositiveIntegerField(default=0, verbose_name='حداقل مبلغ سفارش (تومان)')),
                ('usage_limit', models.PositiveIntegerField(default=1, verbose_name='حداکثر تعداد استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده شده')),
                ('valid_from', models.DateTimeField(verbose_name='معتبر از تاریخ')),
                ('valid_until', models.DateTimeField(verbose_name='معتبر تا تاریخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
            ],
            options={
                'verbose_name': 'کوپن تخفیف',
                'verbose_name_plural': 'کوپن\u200cهای تخفیف',
            },
        ),
        migrations.AlterModelOptions(
            name='usercoupon',
            options={'verbose_name': 'کوپن کاربر', 'verbose_name_plural': 'کوپن\u200cهای کاربر'},
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='used',
            field=models.BooleanField(default=False, verbose_name='استفاده شده'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='code',
            field=models.CharField(max_length=50, verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='discount',
            field=models.PositiveIntegerField(help_text='مبلغ تخفیف (تومان)', verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='انقضا در'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال است'),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='account.coupon', verbose_name='کوپن'),
        ),
    ]
