# Generated by Django 4.2.16 on 2026-04-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='نام سایت')),
                ('site_url', models.URLField(verbose_name='آدرس سایت')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='لوگوی سایت')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='فاوآیکون سایت')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='اینستاگرام')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='تلگرام')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='توییتر')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لینکدین')),
                ('footer_text', models.TextField(verbose_name='متن فوتر')),
                ('about_text', models.TextField(verbose_name='درباره ما')),
                ('seo_keywords', models.TextField(blank=True, null=True, verbose_name='کلمات کلیدی سئو')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='توضیحات سئو')),
                ('shipping_cost', models.PositiveIntegerField(default=0, verbose_name='هزینه ارسال')),
                ('free_shipping_threshold', models.PositiveIntegerField(default=0, verbose_name='حداقل خرید برای ارسال رایگان')),
                ('tax_percentage', models.FloatField(default=9.0, verbose_name='درصد مالیات')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان صفحه')),
                ('slug', models.SlugField(unique=True, verbose_name='نامک')),
                ('content', models.TextField(verbose_name='محتوای صفحه')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان سئو')),
                ('seo_keywords', models.TextField(blank=True, null=True, verbose_name='کلمات کلیدی سئو')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='توضیحات سئو')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'صفحه استاتیک',
                'verbose_name_plural': 'صفحات استاتیک',
            },
        ),
    ]
