# Generated by Django 4.2.16 on 2026-04-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'site setting', 'verbose_name_plural': 'site settings'},
        ),
        migrations.AlterModelOptions(
            name='staticpage',
            options={'verbose_name': 'static page  ', 'verbose_name_plural': 'static pages  '},
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(verbose_name='about_text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(verbose_name='Owner address'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Owner email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='needed to hard refresh <--> (shift + f5)', null=True, upload_to='settings/', verbose_name='favicon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(verbose_name='footer text '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='free_shipping_threshold',
            field=models.PositiveIntegerField(default=0, verbose_name='free_shipping_threshold'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='linkedin'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='site logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Owner phone'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='seo_description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='seo_keywords'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='shipping_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='shipping_cost'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(max_length=100, verbose_name='site name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_url',
            field=models.URLField(verbose_name='site url'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tax_percentage',
            field=models.FloatField(default=9.0, verbose_name='tax_percentage'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='telegram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='twitter'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=models.TextField(verbose_name='page content'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='seo_description'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='seo_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='seo_keywords'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='seo_title'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='page slug'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='page title '),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
    ]
